name: flutter_login_template
description: A starter code for flutter apps with auth.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^6.0.3
  flutter_bloc: ^6.0.5
  equatable: ^1.2.5
  authentication_repository:
    path: packages/authentication_repository
  google_fonts: ^1.1.0
  formz: ^0.3.1
  font_awesome_flutter: ^8.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/

